In [2]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [5]:
arr1 = np.array([[1, 2], [3, 4]])
arr1

array([[1, 2],
       [3, 4]])

In [11]:
print(arr1[0][1])
print(arr1[0, 1])
print(arr1[1, 1])

2
2
4


In [21]:
arr1 = np.zeros((3, 2))
arr1

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:
np.random.random((3, 3))

array([[0.39859043, 0.27192985, 0.12794838],
       [0.12894553, 0.66977554, 0.95792037],
       [0.26769529, 0.1414916 , 0.35308401]])

In [47]:
# Numpy - Exercises
# 1
a = np.array([[-1, 2, 0, 4], [4, -0.5, 6, 0], [2.6, 0, 7, 8], [3, -7, 4, 2.0]])
print(a[0:2, ::2])

# 2
# b = [[1, 1, 0, 3], [3, 2, 1, 0]]
# for j in range(4):
#   print(a[b[0][j], b[1][j]])
print(a[[1, 1, 0, 3], [3, 2, 1, 0]])

# 3
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.add(a, b))


[[-1.  0.]
 [ 4.  6.]]
[0. 6. 2. 3.]
[[ 6  8]
 [10 12]]


In [49]:
import pandas as pd
arr1 = np.array(['machine', 'learning'])

df = pd.DataFrame(arr1)
print(df)

          0
0   machine
1  learning


In [52]:
d1 = {
  "John": "UG",
  "Amy": "MS",
  "Rick": "UG",
  "Sam": "UG",
}

d2 = {
  "John": 4.0,
  "Amy": 3.9,
  "Rick": 3.56,
  "Sam": 4.0,
}

data = {"Level": d1, 'GPA': d2}

df = pd.DataFrame(data)
print(df)

     Level   GPA
John    UG  4.00
Amy     MS  3.90
Rick    UG  3.56
Sam     UG  4.00


In [58]:
d1 = {x: x for x in range(1, 11)}
d2 = {x: x**2 for x in range(1, 11)}
d3 = {x: x**3 for x in range(1, 11)}
df = pd.DataFrame({"d1": d1, "d2": d2, "d3": d3})
print(df)

    d1   d2    d3
1    1    1     1
2    2    4     8
3    3    9    27
4    4   16    64
5    5   25   125
6    6   36   216
7    7   49   343
8    8   64   512
9    9   81   729
10  10  100  1000
